/* Barbearia Leandro David • melhorias 2026 */
(function(){
const originalSolicitar=window.solicitarAgendamento;
const originalEntrar=window.entrarAdminRestrito;
window.mostrarSecaoAdmin=function(id,btn){document.querySelectorAll('.admin-section').forEach(x=>x.classList.remove('active-section'));document.getElementById(id)?.classList.add('active-section');document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})};
window.abrirModuloAdminPro=function(id,btn){document.querySelectorAll('.moduloAdmin').forEach(x=>x.classList.add('hidden'));document.getElementById(id)?.classList.remove('hidden');document.querySelectorAll('.module-tabs button').forEach(x=>x.classList.remove('active'));btn?.classList.add('active')};
window.calcularTextoTempo=function(a){if(a.status==='aguardando')return'Aguardando confirmação da barbearia.';if(a.status==='recusado')return'Agendamento não confirmado.';if(a.status==='finalizado')return'Atendimento finalizado. Até a próxima!';if(a.status==='em_atendimento')return'Você está em atendimento agora.';if(!a.hora_prevista)return'Horário previsto ainda não calculado.';const alvo=new Date(`${String(a.data_agendamento).slice(0,10)}T${formatarHora(a.hora_prevista)}:00`);const min=Math.round((alvo-new Date())/60000);if(min>0)return`Faltam aproximadamente ${min} minutos.`;if(min>-20)return'Seu horário está chegando. Dirija-se à barbearia.';return'O horário previsto já passou. Consulte a barbearia.'};
window.acompanharCliente=async function(){const busca=safe('telefoneBusca'),cad=safe('clienteTelefone');let telefone=(busca?.value||cad?.value||'').trim();if(!telefone)return alert('Informe seu WhatsApp');if(busca)busca.value=telefone;const {data,error}=await client.from('agendamentos').select('*,clientes!inner(nome,telefone),servicos(nome,duracao_minutos,valor),barbeiros(nome)').eq('clientes.telefone',telefone).in('status',['aguardando','aceito','confirmado','proximo','em_atendimento']).order('data_agendamento',{ascending:true}).order('hora_solicitada',{ascending:true});if(error){console.error(error);return alert('Não foi possível consultar agora')}const meu=(data||[])[0];if(!meu){renderCliente([]);return}let anterior=null;if(meu.barbeiro_id){const {data:fila=[]}=await client.from('agendamentos').select('*,clientes(nome),servicos(nome,duracao_minutos),barbeiros(nome)').eq('data_agendamento',meu.data_agendamento).eq('barbeiro_id',meu.barbeiro_id).in('status',['aceito','confirmado','proximo','em_atendimento']).order('hora_prevista',{ascending:true}).order('hora_solicitada',{ascending:true});const idx=fila.findIndex(x=>x.id===meu.id);if(idx>0)anterior=fila[idx-1];if(!anterior)anterior=fila.find(x=>x.status==='em_atendimento')||null}renderCliente([meu],anterior)};
window.carregarPainel=async function(){if(!safe('dataPainel'))return;const data=safe('dataPainel').value||dataHoje();safe('dataPainel').value=data;const {data:lista,error}=await client.from('agendamentos').select('*,clientes(nome,telefone),servicos(nome,duracao_minutos,valor),barbeiros(nome)').eq('data_agendamento',data).order('hora_solicitada',{ascending:true});if(error){console.error(error);return alert('Erro ao carregar painel')}renderPainel(lista||[]);carregarAgendaSemanal();carregarRecepcao();carregarCaixa();carregarReceitaBarbeiros();await carregarDashboard()};
window.gerarHorarios=async function(){if(!safe('horaSolicitada')||!safe('dataAgendamento'))return;const data=safe('dataAgendamento').value||dataHoje();const barbeiro_id=safe('barbeiroSelect')?.value||'';const telefone=safe('clienteTelefone')?.value?.trim()||'';if(!barbeiro_id){safe('horaSolicitada').innerHTML='<option value="">Escolha um barbeiro</option>';return}if(telefone){const {data:ja=[]}=await client.from('agendamentos').select('id,clientes!inner(telefone)').eq('data_agendamento',data).eq('clientes.telefone',telefone).in('status',['aguardando','aceito','confirmado','proximo','em_atendimento']);if(ja.length){safe('horaSolicitada').innerHTML='<option value="">Você já tem agendamento neste dia</option>';return}}const {data:agenda=[]}=await client.from('agendamentos').select('hora_solicitada,status,barbeiro_id').eq('data_agendamento',data).eq('barbeiro_id',barbeiro_id);const ocupados=new Set(agenda.filter(a=>!['cancelado','recusado'].includes(a.status)).map(a=>String(a.hora_solicitada).slice(0,5)));const agora=agoraLaguna(),hoje=dataHoje();let op=[];for(let h=8;h<=20;h++){const hs=h===8?['08:30']:h===20?['20:00']:[`${String(h).padStart(2,'0')}:00`,`${String(h).padStart(2,'0')}:30`];for(const hora of hs){if(ocupados.has(hora))continue;if(data===hoje){const [hh,mm]=hora.split(':').map(Number);const alvo=new Date(agora);alvo.setHours(hh,mm,0,0);if(alvo.getTime()<agora.getTime()+20*60000)continue}op.push(`<option value="${hora}">${hora}</option>`)}}safe('horaSolicitada').innerHTML=op.join('')||'<option value="">Sem horários disponíveis</option>'};
window.solicitarAgendamento=async function(){const btn=document.getElementById('btnAgendar'),old=btn?.innerHTML;if(btn){btn.disabled=true;btn.textContent='Enviando...'}try{await originalSolicitar()}finally{if(btn){btn.disabled=false;btn.innerHTML=old}}};
window.entrarAdminRestrito=async function(){const btn=document.querySelector('#loginAdmin .btn-primary'),old=btn?.innerHTML;if(btn){btn.disabled=true;btn.textContent='Entrando...'}try{await originalEntrar()}finally{if(btn){btn.disabled=false;btn.innerHTML=old}}};
const enhance=()=>{const tel=safe('clienteTelefone'),busca=safe('telefoneBusca');tel?.addEventListener('input',()=>{if(busca)busca.value=tel.value});safe('senhaUsuario')?.addEventListener('keydown',e=>{if(e.key==='Enter')window.entrarAdminRestrito()});safe('loginUsuario')?.addEventListener('keydown',e=>{if(e.key==='Enter')safe('senhaUsuario')?.focus()})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();
