(()=>{
const $=id=>document.getElementById(id);
const hoje=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const moeda=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let db=null,auth=null;
function mensagem(txt,tipo='warn'){const e=$('loginMsg');if(e){e.textContent=txt;e.className=`mensagem ${tipo}`}}
function iniciar(){if(!window.firebase||!window.FB_CONFIG?.apiKey)return false;try{if(!firebase.apps.length)firebase.initializeApp(window.FB_CONFIG);auth=firebase.auth();db=firebase.firestore();return true}catch(e){console.error(e);return false}}
async function carregarAgenda(){const data=$('dataPainel').value;const box=$('agendaDia');try{const snap=await db.collection('agendamentos').where('data','==',data).get();const itens=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.hora).localeCompare(String(b.hora)));$('kpiTotal').textContent=itens.length;$('kpiPendentes').textContent=itens.filter(x=>x.status==='pendente').length;$('kpiFinalizados').textContent=itens.filter(x=>x.status==='finalizado').length;$('kpiReceita').textContent=moeda(itens.filter(x=>x.status==='finalizado').reduce((s,x)=>s+Number(x.valor||0),0));$('statusAdmin').textContent=`Firebase conectado • ${itens.length} agendamento(s)`;if(!itens.length){box.className='empty';box.textContent='Nenhum agendamento encontrado.';return}box.className='';box.innerHTML=itens.map(x=>`<article class="agenda-item"><div><strong>${x.hora} • ${x.nome||'Cliente'}</strong><span>${x.telefone||''}</span><small>${x.servico_id||''} • ${x.status||'pendente'}</small></div><div><button class="secondary" data-id="${x.id}" data-status="confirmado">Confirmar</button><button class="secondary" data-id="${x.id}" data-status="finalizado">Finalizar</button></div></article>`).join('');box.querySelectorAll('button[data-id]').forEach(b=>b.onclick=async()=>{await db.collection('agendamentos').doc(b.dataset.id).update({status:b.dataset.status});carregarAgenda()})}catch(e){console.error(e);$('statusAdmin').textContent='Erro ao consultar o Firestore.'}}
window.addEventListener('DOMContentLoaded',()=>{if($('dataPainel'))$('dataPainel').value=hoje();if(!iniciar()){mensagem('Firebase não configurado.');return}$('btnEntrar').onclick=async()=>{try{await auth.signInWithEmailAndPassword($('email').value.trim(),$('senha').value);mensagem('','ok')}catch(e){mensagem('E-mail ou senha inválidos.','erro')}};$('btnSair').onclick=()=>auth.signOut();$('dataPainel').addEventListener('change',carregarAgenda);auth.onAuthStateChanged(user=>{if(user){$('loginWrap').classList.add('hidden');$('painel').classList.remove('hidden');$('perfil').textContent=user.email||'Admin';carregarAgenda()}else{$('painel').classList.add('hidden');$('loginWrap').classList.remove('hidden')}})});
})();